language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
    - stage: deploy
      script: bash ./travis/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "af862fa96d3e"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: trusty
sudo: false
